from __future__ import annotations

import math
import random
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone


@dataclass(frozen=True)
class Observation:
    observed_at: datetime
    soil_moisture: float
    soil_temperature: float
    air_temperature: float
    humidity: float
    rainfall_mm: float
    source: str = "simulation"


@dataclass(frozen=True)
class FarmState:
    crop: str
    soil_type: str
    crop_stage: float
    irrigation_mm: float
    irrigation_demand_mm: float


@dataclass(frozen=True)
class SimulationStep:
    observation: Observation
    state: FarmState


def calculate_irrigation_demand(
    soil_moisture: float,
    rainfall_mm: float,
) -> float:
    """
    Ground-truth irrigation requirement.

    This is generated by the simulator and must never
    be supplied directly to the ML model.
    """

    if rainfall_mm >= 8.0:
        return 0.0

    target_moisture = 34.0

    deficit = max(
        0.0,
        target_moisture - soil_moisture,
    )

    if deficit <= 1.0:
        return 0.0

    demand = (deficit ** 1.35) * 0.9

    return round(
        min(12.0, demand),
        2,
    )


def simulate(
    start: datetime,
    hours: int,
    seed: int = 42,
) -> list[SimulationStep]:

    rng = random.Random(seed)

    if start.tzinfo is None:
        start = start.replace(
            tzinfo=timezone.utc
        )

    steps: list[SimulationStep] = []

    soil_moisture = 32.0

    crop = "tomato"
    soil_type = "loamy"
    crop_cycle_days = 120

    for hour in range(hours):

        timestamp = (
            start + timedelta(hours=hour)
        )

        hour_of_day = timestamp.hour
        day_index = hour // 24

        # Repeat the crop cycle so the year-long simulator
        # contains multiple realistic growing periods.
        cycle_day = day_index % crop_cycle_days

        crop_stage = (
            cycle_day / crop_cycle_days
        )

        crop_factor = (
            0.65
            + 0.45
            * math.sin(
                math.pi * crop_stage
            )
        )

        # -------------------------
        # WEATHER
        # -------------------------

        seasonal_temperature = (
            26.0
            + 4.0
            * math.sin(
                2
                * math.pi
                * day_index
                / 30
            )
        )

        temperature = (
            seasonal_temperature
            + 6.0
            * math.sin(
                (hour_of_day - 6)
                * math.pi
                / 12
            )
            + rng.gauss(0, 0.7)
        )

        humidity = (
            72.0
            - 18.0
            * math.sin(
                (hour_of_day - 6)
                * math.pi
                / 12
            )
            + rng.gauss(0, 2.0)
        )

        humidity = max(
            20.0,
            min(100.0, humidity),
        )

        rain_probability = (
            0.04
            + 0.04
            * (
                1
                + math.sin(
                    2
                    * math.pi
                    * day_index
                    / 60
                )
            )
            / 2
        )

        # Seasonal rainfall pattern.
        # Multiple dry periods throughout the year allow
        # the simulator to generate realistic water stress.
        month = timestamp.month

        dry_months = {
            1, 2, 3,
            5, 6,
            9, 10,
            12,
        }

        rain_probability = (
            0.025
            if month in dry_months
            else 0.075
        )

        rainfall = 0.0

        if rng.random() < rain_probability:
            rainfall = round(
                rng.uniform(3.0, 25.0),
                2,
            )

        # -------------------------
        # EVAPOTRANSPIRATION
        # -------------------------

        heat_component = max(
            0.0,
            temperature - 18.0,
        )

        humidity_factor = (
            1.0
            + max(
                0.0,
                70.0 - humidity,
            )
            / 140.0
        )

        # Seasonal crop water demand.
        # This creates realistic dry periods across the
        # full growing year instead of concentrating stress
        # only in the first few months.
        month = timestamp.month

        seasonal_factor = {
            1: 0.95,
            2: 1.00,
            3: 1.10,
            4: 1.15,
            5: 1.20,
            6: 1.10,
            7: 0.85,
            8: 0.85,
            9: 1.05,
            10: 1.15,
            11: 1.05,
            12: 0.95,
        }[month]

        evapotranspiration = (
            heat_component
            * 0.055
            * humidity_factor
            * crop_factor
            * seasonal_factor
        )

        # -------------------------
        # GROUND-TRUTH DEMAND
        # -------------------------

        irrigation_demand_mm = (
            calculate_irrigation_demand(
                soil_moisture,
                rainfall,
            )
        )

        irrigation_mm = min(
    irrigation_demand_mm * 0.35,
    3.0,
)

        # -------------------------
        # SOIL WATER BALANCE
        # -------------------------

        infiltration = (
            rainfall * 0.30
        )

        soil_moisture += infiltration
        soil_moisture += (
            irrigation_mm * 0.30
        )

        soil_moisture -= (
            evapotranspiration
        )

        soil_moisture += rng.gauss(
            0,
            0.10,
        )

        soil_moisture = max(
            10.0,
            min(50.0, soil_moisture),
        )

        # -------------------------
        # SOIL TEMPERATURE
        # -------------------------

        soil_temperature = (
            temperature * 0.75
            + 5.0
            + rng.gauss(0, 0.4)
        )

        observation = Observation(
            observed_at=timestamp,
            soil_moisture=round(
                soil_moisture,
                2,
            ),
            soil_temperature=round(
                soil_temperature,
                2,
            ),
            air_temperature=round(
                temperature,
                2,
            ),
            humidity=round(
                humidity,
                2,
            ),
            rainfall_mm=rainfall,
        )

        state = FarmState(
            crop=crop,
            soil_type=soil_type,
            crop_stage=round(
                crop_stage,
                4,
            ),
            irrigation_mm=round(
                irrigation_mm,
                2,
            ),
            irrigation_demand_mm=round(
                irrigation_demand_mm,
                2,
            ),
        )

        steps.append(
            SimulationStep(
                observation=observation,
                state=state,
            )
        )

    return steps


def generate_observations(
    start: datetime,
    hours: int,
    seed: int = 42,
) -> list[Observation]:

    return [
        step.observation
        for step in simulate(
            start,
            hours,
            seed,
        )
    ]


def generate_farm_states(
    start: datetime,
    hours: int,
    seed: int = 42,
) -> list[FarmState]:

    return [
        step.state
        for step in simulate(
            start,
            hours,
            seed,
        )
    ]


if __name__ == "__main__":

    start = datetime.now(
        timezone.utc
    ).replace(
        minute=0,
        second=0,
        microsecond=0,
    )

    for step in simulate(
        start,
        24,
    ):
        print(
            step.observation,
            "| demand_mm=",
            step.state.irrigation_demand_mm,
        )

