"""prevent duplicate field observations

Revision ID: 4eb3eafedc6e
Revises: 0ca7c0e82e96
Create Date: 2026-08-28 10:09:55.156896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb3eafedc6e'
down_revision: Union[str, Sequence[str], None] = '0ca7c0e82e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_field_observation_field_time', 'field_observations', ['field_id', 'observed_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_field_observation_field_time', 'field_observations', type_='unique')
    # ### end Alembic commands ###
