"""add crops and growing seasons

Revision ID: b95e327da37f
Revises: 87dbac7f8fb9
Create Date: 2026-08-27 23:43:22.337428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95e327da37f'
down_revision: Union[str, Sequence[str], None] = '87dbac7f8fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('growing_seasons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('season_name', sa.String(length=100), nullable=False),
    sa.Column('planting_date', sa.Date(), nullable=False),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growing_seasons_crop_id'), 'growing_seasons', ['crop_id'], unique=False)
    op.create_index(op.f('ix_growing_seasons_field_id'), 'growing_seasons', ['field_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_growing_seasons_field_id'), table_name='growing_seasons')
    op.drop_index(op.f('ix_growing_seasons_crop_id'), table_name='growing_seasons')
    op.drop_table('growing_seasons')
    op.drop_table('crops')
    # ### end Alembic commands ###
